theme: "just-the-docs"
markdown: kramdown

# サイトタイトル
title: "物理学Wiki"

# サイドバーのナビゲーション
just_the_docs:
  logo: ""
  aux_links:
    "GitHub Repository": https://github.com/your-username/your-repo
  nav:
    - title: "Home"
      url: "/"
    - title: "Mechanics"
      url: "/mechanics"
    - title: "License"
      url: "/license"
